title: Products
icon: shopping-cart
pages:
  template: product
  sort: flip
files: false
fields:
  title:
    label: Page
    type:  text
    width: 1/3
  subtitle:
    label:
      fr: Titre
      en: Title
    type: text
    width: 2/3