title: Product
pages: true
files:
  sortable: true
fields:
  title:
    label:
      fr: Titre
      en: Title
    type:  text
    width: 3/4
  price:
    label:
      fr: Prix
      en: Price
    type:  text
    width: 1/4
    help:
      fr: Prix TTC si vous utilisez la TVA
      en: Price includes VAT
  soldout:
    label:
      fr: Produit épuisé
      en: Product out of stock
    type: switch
    text: Produit épuisé
    width: 1/2
  cover_image:
    label:
      fr: Image de l'article
      en: Image of the article
    type: image
    width: 1/2
  text:
    label:
      fr: Texte
      en: Text
    type:  textarea
  tags:
    label: Tags
    type:  tags